name: SYNC with Hugging Face
on:
    workflow_run:
        workflows: ["Tests"]
        types:
            - completed


jobs:
    sync:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Python deps
              run: |
                    python -m pip install --upgrade pip
                    pip install huggingface_hub

            - name: Upload folder to Local-Space
              env:
                  HF_Token: ${{ secrets.HF_Token }}
                  HF_LOCAL_SPACE_ID: ${{ secrets.HF_LOCAL_SPACE_ID }}
              run: |
                    python - <<'PY'
                    import os
                    from huggingface_hub import HfApi
                    api = HfApi()
                    api.upload_folder(
                        folder_path=".",
                        path_in_repo=".",
                        repo_id=os.getenv("HF_LOCAL_SPACE_ID"),
                        repo_type="space",
                        token=os.getenv("HF_Token"),
                        ignore_patterns=[".git/*", ".github/*", ".vscode/*", ".idea/*", "__pycache__/*"]
                    )
                    print("Local upload complete.")
                    PY

    sync_api:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout passed commit
              uses: actions/checkout@v4

            - name: Install hub client
              run: pip install --upgrade huggingface_hub

            - name: Use API README for this job
              run: cp README.space-api.md README.md
                    

            - name: Upload to API Space
              env:
                  HF_Token: ${{ secrets.HF_Token }}
                  HF_API_SPACE_ID: ${{ secrets.HF_API_SPACE_ID }}   
              run: |
                    python - <<'PY'
                    import os
                    from huggingface_hub import HfApi
                    api = HfApi()
                    api.upload_folder(
                        folder_path=".",
                        path_in_repo=".",
                        repo_id=os.environ["HF_API_SPACE_ID"],
                        repo_type="space",
                        token=os.environ["HF_Token"],
                        ignore_patterns=[".git/*", ".github/*", ".vscode/*", ".idea/*", "__pycache__/*"]
                    )
                    print("API upload complete.")
                    PY