name: SYNC with Hugging Face
on:
    workflow_run:
        workflows: ["Tests"]
        types:
            - completed


jobs:
    sync:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest
        steps:
            - id: checkout_code
              name: Checkout code
              uses: actions/checkout@v4

            - id: install_deps
              name: Install Python deps
              run: |
                    python -m pip install --upgrade pip
                    pip install huggingface_hub

            - id: notify_discord_checkout
              name: Notify Discord — Checkout Code
              if: ${{ always() }}
              uses: tsickert/discord-webhook@v7.0.0
              with:
                    webhook-url: ${{ secrets.DISCORD }}
                    content: >
                            **${{ github.workflow }} - Local Sync**

                            **Checkout Code:** ${{ steps.checkout_code.outcome == 'success' && 'SUCCESS' || steps.checkout_code.outcome == 'failure' && 'FAILED' || 'SKIPPED' }}

                            **Repository:** ${{ github.repository }}
                            **Branch:** ${{ github.ref_name }}
                            **Commit:** `${{ github.sha }}`
                            **Actor:** ${{ github.actor }}

                            **[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**

                            *Triggered by successful test completion*

            - id: upload_folder
              name: Upload folder to Local-Space
              env:
                  HF_Token: ${{ secrets.HF_Token }}
                  HF_LOCAL_SPACE_ID: ${{ secrets.HF_LOCAL_SPACE_ID }}
              run: |
                    python - <<'PY'
                    import os
                    from huggingface_hub import HfApi
                    api = HfApi()
                    api.upload_folder(
                        folder_path=".",
                        path_in_repo=".",
                        repo_id=os.getenv("HF_LOCAL_SPACE_ID"),
                        repo_type="space",
                        token=os.getenv("HF_Token"),
                        ignore_patterns=[".git/*", ".github/*", ".vscode/*", ".idea/*", "__pycache__/*"]
                    )
                    print("Local upload complete.")
                    PY

            - id: notify_discord_local_upload
              name: Notify Discord - Local Upload
              if: ${{ always() }}
              uses: tsickert/discord-webhook@v7.0.0
              with:
                    webhook-url: ${{ secrets.DISCORD }}
                    content: >
                            **Local Space Upload**

                            **Upload Status:** ${{ steps.upload_folder.outcome == 'success' && 'SUCCESS' || steps.upload_folder.outcome == 'failure' && 'FAILED' || 'SKIPPED' }}

                            **Repository:** ${{ github.repository }}
                            **Branch:** ${{ github.ref_name }}
                            **Commit:** `${{ github.sha }}`
                            **Actor:** ${{ github.actor }}

                            **[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**


    sync_api:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout passed commit
              uses: actions/checkout@v4

            - name: Install hub client
              run: pip install --upgrade huggingface_hub

            - id: use_api_readme
              name: Use API README for this job
              run: cp README.space-api.md README.md
                    
            - id: notify_discord_api_readme
              name: Notify Discord - Use API README
              if: ${{ always() }}
              uses: tsickert/discord-webhook@v7.0.0
              with:
                    webhook-url: ${{ secrets.DISCORD }}
                    content: >
                            **API Space Preparation**

                            **Switch to API README:** ${{ steps.use_api_readme.outcome == 'success' && 'SUCCESS' || steps.use_api_readme.outcome == 'failure' && 'FAILED' || 'SKIPPED' }}

                            **Repository:** ${{ github.repository }}
                            **Branch:** ${{ github.ref_name }}
                            **Commit:** `${{ github.sha }}`
                            **Actor:** ${{ github.actor }}

                            **[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**

            - id: upload_api_space
              name: Upload to API Space
              env:
                  HF_Token: ${{ secrets.HF_Token }}
                  HF_API_SPACE_ID: ${{ secrets.HF_API_SPACE_ID }}   
              run: |
                    python - <<'PY'
                    import os
                    from huggingface_hub import HfApi
                    api = HfApi()
                    api.upload_folder(
                        folder_path=".",
                        path_in_repo=".",
                        repo_id=os.environ["HF_API_SPACE_ID"],
                        repo_type="space",
                        token=os.environ["HF_Token"],
                        ignore_patterns=[".git/*", ".github/*", ".vscode/*", ".idea/*", "__pycache__/*"]
                    )
                    print("API upload complete.")
                    PY
            
            - id: notify_discord_api_upload
              name: Notify Discord - API Upload
              if: ${{ always() }}
              uses: tsickert/discord-webhook@v7.0.0
              with:
                    webhook-url: ${{ secrets.DISCORD }}
                    content: >
                            **API Space Upload**

                            **Upload Status:** ${{ steps.upload_api_space.outcome == 'success' && 'SUCCESS' || steps.upload_api_space.outcome == 'failure' && 'FAILED' || 'SKIPPED' }}

                            **Repository:** ${{ github.repository }}
                            **Branch:** ${{ github.ref_name }}
                            **Commit:** `${{ github.sha }}`
                            **Actor:** ${{ github.actor }}

                            **[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**

                            *API Space deployment complete!*