name: Tests

on: 
    - push
    - pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with: 
                  python-version: '3.10'

            - id: install_deps
              name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            
            - id: notify_discord_install_deps
              name: Notify Discord - Install Dependencies
              if: ${{ always() }}
              uses: tsickert/discord-webhook@v7.0.0
              with:
                    webhook-url: ${{ secrets.DISCORD }}
                    content: >
                            **${{ github.workflow }}**

                            **Install Dependencies:** ${{ steps.install_deps.outcome == 'success' && 'SUCCESS' || steps.install_deps.outcome == 'failure' && 'FAILED' || 'SKIPPED' }}

                            **Repository:** ${{ github.repository }}
                            **Branch:** ${{ github.ref_name }}
                            **Commit:** `${{ github.sha }}`
                            **Actor:** ${{ github.actor }}

                            **[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**

            - id: run_tests
              name: Run tests
              run: pytest --disable-warnings -q
            
            - name: Summarize runs_local.csv (if present)
              if: ${{ always() }}
              run: |
                python - <<'PY'
                import os, json
                from utils_media import summarize_csv
                p = "fusion-app/runs_local.csv"
                if os.path.exists(p):
                    s = summarize_csv(p)
                    open("runs_local.summary.json","w").write(json.dumps(s, indent=2))
                PY

            - name: Upload run logs
              if: ${{ always() }}
              uses: actions/upload-artifact@v4
              with:
                name: runs-local-${{ github.run_number }}-${{ github.sha }}
                path: |
                  fusion-app/runs_local.csv
                  runs_local.summary.json
                if-no-files-found: ignore
                retention-days: 14

            - id: notify_discord_tests
              name: Notify Discord - Run Tests
              if: ${{ always() }}
              uses: tsickert/discord-webhook@v7.0.0
              with:
                    webhook-url: ${{ secrets.DISCORD }}
                    content: >
                            **${{ github.workflow }} - Test Results**

                            **Run Tests:** ${{ steps.run_tests.outcome == 'success' && 'SUCCESS' || steps.run_tests.outcome == 'failure' && 'FAILED' || 'SKIPPED' }}

                            **Repository:** ${{ github.repository }}
                            **Branch:** ${{ github.ref_name }}
                            **Commit:** `${{ github.sha }}`
                            **Actor:** ${{ github.actor }}

                            **[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})**

